### PR TITLE
Deployment test

### PR DESCRIPTION
**Pull request by vladvlad00**
Nu trebuie dat merge inca, pull request-ul e facut doar ca sa isi dea trigger workflow-ul

### CODE REVIEW

**Comment by vladvlad00** [comment]
Task linked: [CU-kmrdpg Migrate to Click-up](https://app.clickup.com/t/kmrdpg)

**Comment by vladvlad00** [comment]
acum pare sa mearga totul

**Comment by vladvlad00** [comment]
..

**Comment by vladvlad00** [comment]
test

**Comment by vladvlad00** [comment]
test2

**Comment by vladvlad00** [comment]
test4

**Comment by vladvlad00** [comment]
test56

**Review by robertadriang — APPROVED** [review]
Uochei

**Review by JohnBordea — COMMENTED** [review]
Bine.

**Pull request merged**
